version: '3.8'

services:
  incallup:
    build: .
    ports:
      - "80:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 4booiVOPDhVws59d2
      MYSQL_DATABASE: incallup_db
      MYSQL_USER: incallup_incallup
      MYSQL_PASSWORD: B=3hX4SkiNE,
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: